Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: boroscsaba-my-bucket123
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      Tags:
        - Key: project
          Value: test-project-tag

  wwwBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: www.boroscsaba-my-bucket123
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref Bucket
          Protocol: http
      Tags:
        - Key: project
          Value: test-project-tag

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub arn:aws:s3:::${Bucket}/*

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: static_website_access_control
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt Bucket.RegionalDomainName
            Id: !GetAtt Bucket.RegionalDomainName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: !GetAtt Bucket.RegionalDomainName
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        Enabled: true
      Tags:
        - Key: project
          Value: test-project-tag